name: thefuck
version: stable
version-script: git -C parts/thefuck/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Fuck tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  thefuck:
    command: bin/thefuck
    environment:
        PYTHONIOENCODING: utf-8
  fuck:
    command: bin/fuck
    environment:
        PYTHONIOENCODING: utf-8

parts:
  thefuck:
    source: https://github.com/Radiump123/thefuck-py3.12.x.git
    plugin: python
